resolver: lts-10.2
packages:
- core/
- hunit/
- quickcheck/
- smallcheck/
- core-tests/
extra-deps:
- optparse-applicative-0.14.0.0
- unbounded-delays-0.1.1.0
# this is needed for travis, because call-stack is absent from the old snapshots
- call-stack-0.1.0
flags: {}
